repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest tests
      language: system
      types: [python]
      pass_filenames: false
