name: 'Gitcha AI'
branding:
  icon: 'edit'
  color: 'green'
description: 'Generate OpenAI answers based on the entire curriculum vitae files in your repository (PDFs, Docs, Markdown etc.)'
inputs:
  repo-token:
    description: 'GitHub repo token'
    required: true
  open-ai-key: 
    description: 'Secret key of OpenAI API'
    required: true
  action: 
    description: 'What kind of action: "letter-of-application" or "prompt"'
    required: true
    default: 'prompt'

outputs:
  answer: # id of output
    description: 'The generated answer'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/shry/gitcha-action:latest'
  env:
    OPENAI_API_KEY: ${{ inputs.open-ai-key }}
    GIT_PROVIDER_API_TOKEN: ${{ inputs.repo-token }}
    GIT_PROVIDER: github
    GITCHA_ACTION: ${{ inputs.action }}
