name: 'Curriculum vitae'
branding:
  icon: 'edit'
  color: 'green'
description: 'Create a letter of application out of all the valid repo files'
inputs:
  repo-token:
    description: 'GitHub repo token'
    required: true
  open-ai-key: 
    description: 'Secret key of OpenAI API'
    required: true
  action: 
    description: 'What kind of action: "letter-of-application" or "prompt"'
    required: true
    default: 'letter-of-application'

outputs:
  answer: # id of output
    description: 'The generated answer'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.open-ai-key }}
    GIT_PROVIDER_API_TOKEN: ${{ inputs.repo-token }}
    GIT_PROVIDER: github
    GITCHA_ACTION: ${{ inputs.action }}
